language: java
 
services:
  - docker
 
jdk:
  - openjdk11
  
script: "mvn clean package -DskipTests=true"
  
after_success:
- bash <(curl -s https://raw.githubusercontent.com/sesam-community/guidelines/BaardBouvet-patch-1/after_success.sh)
